name: Run JavaScript every minute

on:
  schedule:
    - cron: "*/1 * * * *" # اجرای هر دقیقه

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # یا نسخه دیگر جاوااسکریپت

    - name: Run the JavaScript file
      run: node index.js
